export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';
export const SET_AUTH_REDIRECT_PATH = 'SET_AUTH_REDIRECT_PATH';

export const FETCH_ENTITY_PARENT_FILES = 'FETCH_ENTITY_PARENT_FILES';
export const FETCH_VIEW_PARENT_FILES = 'FETCH_VIEW_PARENT_FILES';

export const CREATE_ENTITY = 'CREATE_ENTITY';
export const FETCH_ENTITIES = 'FETCH_ENTITIES';
export const FETCH_ENTITY = 'FETCH_ENTITY';
export const EDIT_ENTITY = 'EDIT_ENTITY';
export const DELETE_ENTITY = 'DELETE_ENTITY';

export const CREATE_PROJECT_GROUP = 'CREATE_PROJECT_GROUP';
export const FETCH_PROJECT_GROUPS = 'FETCH_PROJECT_GROUPS';
export const FETCH_PROJECT_GROUP = 'FETCH_PROJECT_GROUP';
export const EDIT_PROJECT_GROUP = 'EDIT_PROJECT_GROUP';
export const DELETE_PROJECT_GROUP = 'DELETE_PROJECT_GROUP';

export const CREATE_FEATURE = 'CREATE_FEATURE';
export const FETCH_FEATURES = 'FETCH_FEATURES';
export const FETCH_FEATURE = 'FETCH_FEATURE';
export const EDIT_FEATURE = 'EDIT_FEATURE';
export const DELETE_FEATURE = 'DELETE_FEATURE';

export const CREATE_VIEW = 'CREATE_VIEW';
export const FETCH_VIEWS = 'FETCH_VIEWS';
export const FETCH_VIEW = 'FETCH_VIEW';
export const EDIT_VIEW = 'EDIT_VIEW';
export const DELETE_VIEW = 'DELETE_VIEW';

export const CREATE_PROJECT = 'CREATE_PROJECT';
export const FETCH_PROJECTS = 'FETCH_PROJECTS';
export const FETCH_PROJECT = 'FETCH_PROJECT';
export const EDIT_PROJECT = 'EDIT_PROJECT';
export const DELETE_PROJECT = 'DELETE_PROJECT';

export const CREATE_ENTITY_FILES = 'CREATE_ENTITY_FILES';
export const CREATE_LOOKUP_FILES = 'CREATE_LOOKUP_FILES';
export const CREATE_VIEW_FILES = 'CREATE_VIEW_FILES';
export const CREATE_COMMON_FILES = 'CREATE_COMMON_FILES';
export const CREATE_CONFIG_FILES = 'CREATE_CONFIG_FILES';
export const CREATE_ERROR_FILES = 'CREATE_ERROR_FILES';
