export const A_PROJECT_REMOVED_FROM_ITEM = 'A_PROJECT_REMOVED_FROM_ITEM';

export const ADD_PROJECTS_OF_A_GIVEN_PROJECTGROUP_TO_SOURCE_PROJECTS =
  'ADD_PROJECTS_OF_A_GIVEN_PROJECTGROUP_TO_SOURCE_PROJECTS';
export const ADD_NEW_PROJECTS_WHEN_ON_CREATE_MODE =
  'ADD_NEW_PROJECTS_WHEN_ON_CREATE_MODE';
export const ADD_NEW_PROJECT_WHEN_ON_EDIT_MODE =
  'ADD_NEW_PROJECT_WHEN_ON_EDIT_MODE';

export const GPY_PROJECTS_OR_ITEM_PROJECTS_UPDATED =
  'GPY_PROJECTS_OR_ITEM_PROJECTS_UPDATED';

export const SET_PROJECTS_OF_THE_ITEM = 'SET_PROJECTS_OF_THE_ITEM';
export const SET_SELECTED_NEW_PROJECT = 'SET_SELECTED_NEW_PROJECT';
export const SET_SOURCE_AND_TARGET_PROJECTS = 'SET_SOURCE_AND_TARGET_PROJECTS';

export const UPDATE_SELECTED_NEW_PROJECT_WHEN_SOURCE_PROJECTS_UPDATED =
  'UPDATE_SELECTED_NEW_PROJECT_WHEN_SOURCE_PROJECTS_UPDATED';
